### ISSUE TITLE
graph trop lourd pour pouvoir le continuer ?

### ISSUE THREAD

**Issue by ponyBoy-dev** [lipsumar/automotron-v2#2]
Sur https://automotron-v2.lipsumar.io/editor/Qy0GuoYlzj j'arrive plus à continuer. Quand j'essaie de titrer un lien depuis une box, pas moyen de l'étendre de plus de quelques mm. Peut-être est-ce parce que le graph est très long/lourd ? 
Il est estimé à 2 907 294 431 591 575 000 000 000 000 possibilités (c'est marrant comme nombre, hein, je sais pas comment ça se dit).

S'il y a une "limite" à ne pas dépasser, ça pourrait être cool qu'il y ait une indication (un truc t'indique quand le fonctionnement n'est plus garanti que pour 10 nouveaux liens/nouvelles boxes). 
Et qu'on puisse stratégiquement scinder un graph. En choisissant un lien, on clique droit dessus et on a la possibilité 'exporter toute la suite dans un nouveau graph', et ces graphs sont liés mais ne doivent jamais être gérés à la fois d'un coup par la machine. (probablement une feature de la v.3, j'en ai bien conscience).

**Comment by lipsumar** [comment]
il n'y a pas de limite à la taille du graph.

le graph ci-dessus ne fonctionne pas comme il devrait, mais c'est en fait à cause de la grille derrière qui ne tient pas à cette taille. je regarde à corriger ça...

**Comment by lipsumar** [comment]
l'erreur de la grille est réglée
