### ISSUE TITLE
texte trop long pour être affiché en résultat

### ISSUE THREAD

**Issue by ponyBoy-dev** [lipsumar/automotron-v2#4]
Quand le texte est vraiment long, il sort de la box de droite prévue et ne s'affiche pas en entier. Faudrait sans doute lui ajouter un scroll ou redimensionner le texte pour qu'il rentre systématiquement dans la box. 
Observable sur le monstrueux https://automotron-v2.lipsumar.io/editor/Qy0GuoYlzj évidemment.

**Comment by lipsumar** [comment]
résolu
