### ISSUE TITLE
ne reconnait pas les [ ] s'il y a un espace après

### ISSUE THREAD

**Issue by ponyBoy-dev** [lipsumar/automotron-v2#5]
Comme dit dans le titre, si dans une liste on a 
[plante, plantes]
[lapin, lapins]  
S'il y a un espace après la fermeture des crochets, l'automotron, au lieu de comprendre que c'est pour des accords, va croire qu'on veut littéralement la string "[lapin, lapin] " par exemple. Et d'ailleurs, affichera
plante [2]
[lapin, lapins]

**Comment by lipsumar** [comment]
résolu
