### ISSUE TITLE
graph ne run pas

### ISSUE THREAD

**Issue by ponyBoy-dev** [lipsumar/automotron-v2#6]
Ce graph : https://automotron-v2.lipsumar.io/editor/cp7MTJjgP ne run pas. 
Pour que ça run, il faut soit : supprimer le lien entre A et B, soit supprimer l'agreement entre B et C. Le fait que D soit freezé ou pas ne change rien.

NB: ne pas faire attention aux trucs pas reliés, c'est pour plus tard.

**Comment by lipsumar** [comment]
la node "que tu" est mal accordée. L'accord `(s)` n'a pas de sens, car le premier terme est `gender`, pas `number`.

L'accord devrait être `(number=s)`

**Comment by lipsumar** [comment]
rouvre l'issue si d'autres problèmes
