### ISSUE TITLE
graph qui boucle sur lui-même = plantage

### ISSUE THREAD

**Issue by ponyBoy-dev** [lipsumar/automotron-v2#7]
Au lieu de faire un message d'alerte, si on fait par inadvertance un graph qui boucle sur lui-même, ça plante com-plè-te-ment la page. 

Ici, j'ai refait un cas simple (donc personne ne ferait ça dans la vraie vie, c'est juste pour illustrer le cas qui m'est arrivé en ne réalisant pas ce que je faisais, dans un graph beaucoup plus messy) :
https://automotron-v2.lipsumar.io/editor/v9191650W
=> si on link to generator A vers B, c'est la fin de tout. 
Mignonnement, la box de résultat indique qu'il y a une infinité de possibilités. (ce qui n'est pas vrai à mon avis, il y a juste une infinité de mots à rendre).

**Comment by lipsumar** [comment]
le graph prend maintenant en compte les boucles infinies. il montrera une erreur et s'arrêtera.
