### ISSUE TITLE
accents font planter les accords

### ISSUE THREAD

**Issue by ponyBoy-dev** [lipsumar/automotron-v2#8]
si on a une liste
rapé (rime=é)
volé (rime=é) 
foutu (rime=u)
bourru (rime=u)
qui doit s'accorder avec une autre
nez (rime=é)
thé (rime=é)
plu (rime=u)
su (rime=u),
l'accord ne marche pas. 
Je crois qu'il ne comprend d'ailleurs même pas que la string entre parenthèses sert à l'accord).

Si on remplace "é" par "er" (dans les accords, pas dans les termes à proprement parler, eux supportent les accents), ça fonctionne.

**Comment by lipsumar** [comment]
résolu
